import React from 'react'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'

function Terms() {
  return (
    <div className="Terms text-white">
      <Navbar />
      <h1 className='text-6xl font-bold'>TERMS {'&'} CONDITIONS</h1>
      <h4>Posted March 23/22</h4>

      <p className='my-8 block'>Monastery Gyatso NFT is a collection of digital caps based on our physical cap, The Gyatso. It runs as a non-fungible token on the ETHEREUM BLOCKCHAIN. Monasterynft.com is the only webpage to mint this NFT. Later on, it will be available on secondary markets like OpenSea. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Additionally, it is essential to mention that it is impossible to undo, reverse or restore any transactions as the Monastery Gyatso NFT smart contract runs on the Ethereum network. </p>
      <p className='my-8 block'>Monastery Gyatso NFT is a collection of digital caps based on our physical cap, The Gyatso. It runs as a non-fungible token on the ETHEREUM BLOCKCHAIN. Monasterynft.com is the only webpage to mint this NFT. Later on, it will be available on secondary markets like OpenSea. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Additionally, it is essential to mention that it is impossible to undo, reverse or restore any transactions as the Monastery Gyatso NFT smart contract runs on the Ethereum network. </p>
      <p className='my-8 block'>Monastery Gyatso NFT is a collection of digital caps based on our physical cap, The Gyatso. It runs as a non-fungible token on the ETHEREUM BLOCKCHAIN. Monasterynft.com is the only webpage to mint this NFT. Later on, it will be available on secondary markets like OpenSea. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Additionally, it is essential to mention that it is impossible to undo, reverse or restore any transactions as the Monastery Gyatso NFT smart contract runs on the Ethereum network. </p>
      <p className='my-8 block'>Monastery Gyatso NFT is a collection of digital caps based on our physical cap, The Gyatso. It runs as a non-fungible token on the ETHEREUM BLOCKCHAIN. Monasterynft.com is the only webpage to mint this NFT. Later on, it will be available on secondary markets like OpenSea. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Additionally, it is essential to mention that it is impossible to undo, reverse or restore any transactions as the Monastery Gyatso NFT smart contract runs on the Ethereum network. </p>
    
      <Footer />
    </div>
  )
}

export default Terms